
public class Choices extends javax.swing.JFrame {

   
    public Choices() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        A = new javax.swing.JLabel();
        Enter = new javax.swing.JTextField();
        date2 = new javax.swing.JButton();
        Stay = new javax.swing.JButton();
        Accept = new javax.swing.JButton();
        B = new javax.swing.JLabel();
        num1 = new javax.swing.JLabel();
        prompt1 = new javax.swing.JLabel();
        prompt2 = new javax.swing.JLabel();
        prompt3 = new javax.swing.JLabel();
        prompt4 = new javax.swing.JLabel();
        prompt5 = new javax.swing.JLabel();
        prompt6 = new javax.swing.JLabel();
        Screen1 = new javax.swing.JLabel();
        Screen2 = new javax.swing.JLabel();
        Screen3 = new javax.swing.JLabel();
        Screen4 = new javax.swing.JLabel();
        Screen5 = new javax.swing.JLabel();
        again = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        house = new javax.swing.JToggleButton();
        Film = new javax.swing.JToggleButton();
        date = new javax.swing.JToggleButton();
        num = new javax.swing.JTextField();
        direction = new javax.swing.JLabel();
        Angel = new javax.swing.JToggleButton();
        prompt7 = new javax.swing.JLabel();
        level = new javax.swing.JToggleButton();
        prompt8 = new javax.swing.JLabel();
        job = new javax.swing.JToggleButton();
        prompt9 = new javax.swing.JLabel();
        Leave = new javax.swing.JToggleButton();
        prompt10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("-Education software-");
        jLabel1.setToolTipText("");

        A.setText("...");

        Enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterActionPerformed(evt);
            }
        });

        date2.setText("blind date");
        date2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date2ActionPerformed(evt);
            }
        });

        Stay.setText("Stay");
        Stay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StayActionPerformed(evt);
            }
        });

        Accept.setText("Accept");
        Accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptActionPerformed(evt);
            }
        });

        B.setText("...");

        num1.setText("Choose a number from 1 or 2  and write in the Textfield");

        prompt1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        prompt2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        prompt3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        prompt4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        prompt5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        prompt6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        Screen1.setText("Life choices");

        again.setText("Start");
        again.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                againActionPerformed(evt);
            }
        });

        jToggleButton1.setText("A");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("B");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        house.setText("House");
        house.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                houseActionPerformed(evt);
            }
        });

        Film.setText("Flim");
        Film.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilmActionPerformed(evt);
            }
        });

        date.setText("No blind date");
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });

        direction.setText("...");

        Angel.setText("Angel");
        Angel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AngelActionPerformed(evt);
            }
        });

        prompt7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        level.setText("level up");
        level.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levelActionPerformed(evt);
            }
        });

        prompt8.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        job.setText("Long job");
        job.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobActionPerformed(evt);
            }
        });

        prompt9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        Leave.setText("reverse");
        Leave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeaveActionPerformed(evt);
            }
        });

        prompt10.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        prompt10.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Screen5)
                                    .addComponent(Screen1)
                                    .addComponent(Screen3)
                                    .addComponent(Screen4)
                                    .addComponent(Screen2)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(num1)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jToggleButton1)
                                        .addComponent(jToggleButton2))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(91, 91, 91)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(A)
                                                .addComponent(B)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addComponent(again, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Enter, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(direction))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(job)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(prompt9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Leave)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(prompt10))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Film)
                                    .addComponent(date)
                                    .addComponent(house)
                                    .addComponent(Accept)
                                    .addComponent(date2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Angel)
                                    .addComponent(level)
                                    .addComponent(Stay, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(114, 114, 114)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(prompt8)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(prompt1)
                                        .addComponent(prompt2))
                                    .addComponent(prompt6)
                                    .addComponent(prompt3)
                                    .addComponent(prompt5)
                                    .addComponent(prompt4)
                                    .addComponent(prompt7))))
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(419, 419, 419))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(again)
                        .addGap(344, 344, 344))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Screen4)
                        .addGap(394, 394, 394))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Screen1)
                        .addGap(18, 18, 18)
                        .addComponent(Screen5)
                        .addGap(28, 28, 28)
                        .addComponent(Screen2)
                        .addGap(32, 32, 32)
                        .addComponent(Screen3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jToggleButton1)
                            .addComponent(A))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jToggleButton2)
                            .addComponent(B))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(num1)
                            .addComponent(job)
                            .addComponent(prompt9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Leave)
                            .addComponent(prompt10)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(house)
                            .addComponent(prompt1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Film)
                            .addComponent(prompt2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(date)
                            .addComponent(prompt3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(date2)
                            .addComponent(prompt4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Stay)
                            .addComponent(prompt5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Angel)
                            .addComponent(prompt6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Accept)
                            .addComponent(prompt7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(level)
                            .addComponent(prompt8))
                        .addGap(105, 105, 105)))
                .addGap(5, 5, 5)
                .addComponent(direction)
                .addGap(12, 12, 12)
                .addComponent(Enter, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterActionPerformed

    private void againActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_againActionPerformed
        //Declare variables
        String answer;
        int number;
        //Get the number from User
        number = Integer.parseInt(num.getText());
        if(again.getText().equals("Restart")){
        //Format all the name of button
        Stay.setText("Stay");
        date.setText("No blind date");
        house.setText("House");
        Film.setText("Flim");
        date2.setText("blind date");
        Angel.setText("Angel");
        level.setText("level up");
        job.setText("long job");
        Leave.setText("reverse");
        Accept.setText("Accept");
        prompt1.setText("");
        prompt2.setText("");
        prompt3.setText("");
        prompt4.setText("");
        prompt5.setText("");
        prompt6.setText("");
        prompt7.setText("");
        prompt8.setText("");
        prompt9.setText("");
        prompt10.setText("");
        again.setText("Start");
        Enter.setText("");
        switch(number){            // Different choices have different results
            case 1:
            Screen1.setText("When you reach middle age, what do you do once you face a hair loss crisis.");
            Screen2.setText("Hair transplant or Shave head");
            Screen3.setText("");
            Screen4.setText("");
            Screen5.setText("");
            //Give you choices
            A.setText(String.valueOf("Hair transplant."));
            B.setText(String.valueOf("Shave head."));
            direction.setText(String.valueOf("Please enter your choice (A/B) in the textfield."));
            again.setText(String.valueOf("Please enter and click again!"));
            answer = Enter.getText();
            if (answer.equals("A") || answer.equals("a")){
                Enter.setText("");
                again.setText("Restart");
                prompt9.setText("<-  Please click here!");
            }
            else if (answer.equals("B") || answer.equals("b")){
                Enter.setText("");
                again.setText("Restart");
                prompt8.setText("<-  Please click here!");
            }
            break;
            case 2:
            Screen1.setText("When you face with the friend's application of a former friend(including ex-girlfriend/boyfriend),");
            Screen2.setText("what will you choose. Accept or Reject if you have a wife/husband.");
            Screen3.setText("");
            Screen4.setText("");
            Screen5.setText("");
            //Give you choices
            A.setText(String.valueOf("Accept"));
            B.setText(String.valueOf("Reject"));
            again.setText(String.valueOf("Please enter and click again!"));
            direction.setText(String.valueOf("Your choice (A/B) will appear in the textfield."));
            //Get the answer form the user
            answer = Enter.getText();
            if (answer.equals("A") || answer.equals("a")){
                prompt7.setText("<-  Please click here!");
                Enter.setText("");
                again.setText(String.valueOf("Restart"));
            }
            else if (answer.equals("B") || answer.equals("b")){
                Enter.setText("");
                prompt1.setText("<-  Please click here!");
                again.setText(String.valueOf("Restart"));
            }
            break;
        }
        }
        else{
        //switch expression
        switch(number){
            case 1:
            Screen1.setText("When you reach middle age, what do you do once you face a hair loss crisis.");
            Screen2.setText("");
            Screen3.setText("");
            Screen4.setText("");
            Screen5.setText("");
            //Give you choices
            A.setText(String.valueOf("Hair transplant."));
            B.setText(String.valueOf("Shave head."));
            direction.setText(String.valueOf("Please enter your choice (A/B) in the textfield."));
            again.setText(String.valueOf("Please enter and click again!"));
            answer = Enter.getText();
            if (answer.equals("A") || answer.equals("a")){
                Enter.setText("");
                again.setText("Restart");
                prompt9.setText("<-  Please click here!");
            }
            else if (answer.equals("B") || answer.equals("b")){
                Enter.setText("");
                again.setText("Restart");
                prompt8.setText("<-  Please click here!");
            }
            break;
            case 2:
            Screen1.setText("When you face with the friend's application of a former friend(including ex-girlfriend/boyfriend),");
            Screen2.setText("what will you choose. Accept or Reject if you have a wife/husband.");
            Screen3.setText("");
            Screen4.setText("");
            Screen5.setText("");
            //Give you choices
            A.setText(String.valueOf("Accept"));
            B.setText(String.valueOf("Reject"));
            again.setText(String.valueOf("Please enter and click again!"));
            direction.setText(String.valueOf("Your choice (A/B) will appear in the textfield."));
            //Get the answer form the user
            answer = Enter.getText();
            if (answer.equals("A") || answer.equals("a")){
                prompt7.setText("<-  Please click here!");
                Enter.setText("");
                again.setText(String.valueOf("Restart"));
            }
            else if (answer.equals("B") || answer.equals("b")){
                Enter.setText("");
                prompt1.setText("<-  Please click here!");
                again.setText(String.valueOf("Restart"));
            }
            break;
        }
        }
    }//GEN-LAST:event_againActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        //Set the Textfield is A
        Enter.setText("A");
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        //Set the Textfield is B
        Enter.setText("B");
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void houseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_houseActionPerformed
        //Declare variables
        String answer;
            Screen1.setText("Because your lover know that you didn't accept friend request,");
            Screen2.setText("your feelings are better than before and you/your lover are pregnant with a second child.");
            Screen3.setText("A few months later, Your eldest son has reached school age and the second child is about to be born. ");
            Screen4.setText("But your house is too small. Now you have two chioces, ");
            Screen5.setText("change a big house or stay here(Here is a studying house which is good for your eldest son to study).");
            house.setText("Make your choice!");
            //Output
            A.setText(String.valueOf("Change a big house."));
            B.setText(String.valueOf("Stay here."));
            answer = Enter.getText(); 
            switch (answer){
                case "A": case "a":
                    //Eliminate redundant text
                    prompt1.setText("");
                    Enter.setText("");
                    //Output
                    Screen1.setText("Unexpected surprise! You have twins from your lover or you.");
                    Screen2.setText("Fortunately, a famous director paid attention to your moment");
                    Screen3.setText("The director wants to find your child to make a movie");
                    Screen4.setText("Do you allow them to join the movie.");
                    Screen5.setText("(If your child are lucky, your child can become an actor) Yes or No");
                    A.setText(String.valueOf("Yes"));
                    B.setText(String.valueOf("No"));
                    if(answer.equals("A") || answer.equals("a")){
                        prompt2.setText("<-  Please click here!");
                    }
                    else if(answer.equals("B") || answer.equals("b")){
                        prompt6.setText("<-  Please click here!");
                    }
                    break;
                case "B": case "b":
                    //Eliminate redundant text
                    Enter.setText("");
                    prompt1.setText("");
                    Screen1.setText("25 years later, because of your choice, your child becomes the director of a business.");
                    Screen2.setText("By the way, your child has reached thirty years old but still not in love.");
                    Screen3.setText("Do you want to help him blind date?");
                    Screen4.setText("Yes or No?");
                    Screen5.setText("");
                    A.setText(String.valueOf("Yes"));
                    B.setText(String.valueOf("No"));
                    if(answer.equals("A") || answer.equals("a")){
                        prompt4.setText("<-  Please click here!");
                    }
                    else if(answer.equals("B") || answer.equals("b")){
                        prompt3.setText("<-  Please click here!");
                    }
                    break;
            }
        
    }//GEN-LAST:event_houseActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        //Story summary
        Screen1.setText("When your child reaches 40 years old, he finally gets married");
        Screen2.setText("You have a son and daughter-in-law who are filial.");
        Screen3.setText("And with the help of your son, you and your wife travel around the world");
        //Eliminate redundant text
        Screen4.setText("");
        Screen5.setText("");
        prompt3.setText("");
        //It's time to end
        Stay.setText("End");
        date.setText("End");
        house.setText("End");
        Film.setText("End");
        date2.setText("End");
        Angel.setText("End");
        level.setText("End");
        job.setText("End");
        Leave.setText("End");
        Accept.setText("End");
    }//GEN-LAST:event_dateActionPerformed

    private void date2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date2ActionPerformed
        //Story summary
        Screen1.setText("You start a blind date for your child through a party, online,etc.");
        Screen2.setText("After a few months, your child was married because of your intervention");
        Screen3.setText("Before you were middle-aged, you got your grandson");
        //Eliminate redundant text
        Screen4.setText("");
        Screen5.setText("");
        //It's time to end
        Stay.setText("End");
        date.setText("End");
        house.setText("End");
        Film.setText("End");
        date2.setText("End");
        Angel.setText("End");
        level.setText("End");
        job.setText("End");
        Leave.setText("End");
        Accept.setText("End");
    }//GEN-LAST:event_date2ActionPerformed

    private void FilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilmActionPerformed
        //Story summary
        Screen1.setText("Condulation, you shock by the elderly entertainment industry");
        Screen2.setText("Although your children have not become actors, they have become a broker in the future.");
        //Eliminate redundant text
        Screen3.setText("You get signature photos of celebrities from time to time, so you shock by the elderly entertainment industry"); 
        Screen4.setText("");
        Screen5.setText("");
        //It's time to end
        Stay.setText("End");
        date.setText("End");
        house.setText("End");
        Film.setText("End");
        date2.setText("End");
        Angel.setText("End");
        level.setText("End");
        job.setText("End");
        Leave.setText("End");
        Accept.setText("End"); 
        prompt2.setText("");
    }//GEN-LAST:event_FilmActionPerformed

    private void AngelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AngelActionPerformed
        //Story summary
        Screen1.setText("You chose to let your child enter the society early");
        Screen2.setText("As time goes by, the twins become doctors");
        //Eliminate redundant text
        Screen3.setText("");
        Screen4.setText("");
        Screen5.setText("");
        //It's time to end
        Stay.setText("End");
        date.setText("End");
        house.setText("End");
        Film.setText("End");
        date2.setText("End");
        Angel.setText("End");
        level.setText("End");
        job.setText("End");
        Leave.setText("End");
        Accept.setText("End");
        prompt5.setText("");
    }//GEN-LAST:event_AngelActionPerformed

    private void AcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptActionPerformed
        //Story summary
        Screen1.setText("Because your lover know that you didn't accept friend request, ");
        Screen3.setText("You have quarreled and divorced.");
        Screen4.setText("Finally lonely and old");
        Screen2.setText("you and your life start to quarrel");
        //Eliminate redundant text
        Screen5.setText("");
        //Output the end
        Stay.setText("End");
        date.setText("End");
        house.setText("End");
        Film.setText("End");
        date2.setText("End");
        Angel.setText("End");
        level.setText("End");
        job.setText("End");
        Leave.setText("End");
        Accept.setText("End");
        prompt6.setText("");
    }//GEN-LAST:event_AcceptActionPerformed

    private void StayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StayActionPerformed
        //Declare variable and Get the choices from user
        String answer = Enter.getText();
        //Eliminate redundant text
        prompt5.setText("");
        //Story summary
        Screen1.setText("Your child chooses to stay abroad");
        Screen2.setText("Few years later, he decide to go back to accompany you");
        //Eliminate redundant text
        Screen3.setText("");
        Screen4.setText("");
        Screen5.setText("");
        //Output the end
        Stay.setText("End");
        date.setText("End");
        house.setText("End");
        Film.setText("End");
        date2.setText("End");
        Angel.setText("End");
        level.setText("End");
        job.setText("End");
        Leave.setText("End");
        Accept.setText("End");
    }//GEN-LAST:event_StayActionPerformed

    private void levelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levelActionPerformed
        //Expand the story
        Screen1.setText("Because company executives are also bald, you get reused");
        Screen2.setText("Your social activities with the outside world have also increased, one day, company activities and your child's birthday is at same day.");
        Screen3.setText("what will you choose! Company activities or child's birthday!");
        //Eliminate redundant text
        Screen4.setText("");
        Screen5.setText("");
        //Give the user choices
        A.setText(String.valueOf("Company activities"));
        B.setText(String.valueOf("Child's birthday"));
        //Get the chioces from the user
        String answer = Enter.getText(); 
        //Introduce flirting stories to users
        switch(answer){
            case "A":case "a":
                //Expand the story
                Screen1.setText("There are many conflicts between you and your child");
                Screen2.setText("Your child grows up and chooses to live alone and stay away from you");
                //Eliminate redundant text
                Screen3.setText("");
                Screen4.setText("");
                Screen5.setText("");
                prompt8.setText("");
                //Output the end
                Stay.setText("End");
                date.setText("End");
                house.setText("End");
                Film.setText("End");
                date2.setText("End");
                Angel.setText("End");
                level.setText("End");
                job.setText("End");
                Leave.setText("End");
                Accept.setText("End");
                break;
            case "B": case "b":
                Screen1.setText("Under your education,");
                Screen2.setText("20 years later, Your son has the opportunity to study and work abroad!");
                Screen3.setText("Make your choices.");
                Screen4.setText("Let the children go home or Stay abroad.");
                Screen5.setText("");
                //Give direction to the user
                prompt5.setText("<-  Please click here!");
                prompt8.setText("");
                break;
        }
    }//GEN-LAST:event_levelActionPerformed

    private void jobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobActionPerformed
        //Expand the story
        Screen1.setText("Hair transplant almost consumes your property.You still have a lot of debt.");
        Screen2.setText("You have a long-term job in your company which is far from your home.");
        //Give the user choices
        Screen3.setText("Do you want to go?");
        Screen4.setText("Yes or No");
        Screen5.setText("");
        A.setText(String.valueOf("Yes"));
        B.setText(String.valueOf("No"));
        //Get the chioces from the user
        String answer = Enter.getText(); 
        switch(answer){
            case "A": case "a":
                prompt9.setText("");
                Screen1.setText("Because you have a long-term job which is far from your home, ");
                Screen2.setText("you miss the best childbearing age");
                Screen3.setText("But advances in technology change your destiny, five years later, you got a son.");
                //Eliminate redundant text
                Screen4.setText("");
                Screen5.setText("");
                //Output the end
                Stay.setText("End");
                date.setText("End");
                house.setText("End");
                Film.setText("End");
                date2.setText("End");
                Angel.setText("End");
                level.setText("End");
                job.setText("End");
                Leave.setText("End");
                Accept.setText("End");
                break;
            case "B": case "b":
                //Eliminate redundant text
                prompt9.setText("");
                //Expand the story
                Screen1.setText("Because of debts, you and your wife often quarrel");
                Screen2.setText("Eventually forced to separate");
                Screen3.setText("Don't worry, the story will reverse in the back");
                //Eliminate redundant text
                Screen4.setText("");
                Screen5.setText("");
                //Give a direction to the user
                prompt10.setText("<-  Please click here!");
                break;
        }
    }//GEN-LAST:event_jobActionPerformed

    private void LeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeaveActionPerformed
                //Story summary        
                Screen1.setText("Unexpectedly, the separation lasted for thirty years");
                Screen2.setText("Finally, at the age of 70, you only can live alone with a bird");
                //Eliminate redundant text
                Screen3.setText("");
                Screen4.setText("");
                Screen5.setText("Tips: No why!");
                //Eliminate redundant text
                prompt10.setText("");
    }//GEN-LAST:event_LeaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Choices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Choices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Choices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Choices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Choices().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A;
    private javax.swing.JButton Accept;
    private javax.swing.JToggleButton Angel;
    private javax.swing.JLabel B;
    private javax.swing.JTextField Enter;
    private javax.swing.JToggleButton Film;
    private javax.swing.JToggleButton Leave;
    private javax.swing.JLabel Screen1;
    private javax.swing.JLabel Screen2;
    private javax.swing.JLabel Screen3;
    private javax.swing.JLabel Screen4;
    private javax.swing.JLabel Screen5;
    private javax.swing.JButton Stay;
    private javax.swing.JToggleButton again;
    private javax.swing.JToggleButton date;
    private javax.swing.JButton date2;
    private javax.swing.JLabel direction;
    private javax.swing.JToggleButton house;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton job;
    private javax.swing.JToggleButton level;
    private javax.swing.JTextField num;
    private javax.swing.JLabel num1;
    private javax.swing.JLabel prompt1;
    private javax.swing.JLabel prompt10;
    private javax.swing.JLabel prompt2;
    private javax.swing.JLabel prompt3;
    private javax.swing.JLabel prompt4;
    private javax.swing.JLabel prompt5;
    private javax.swing.JLabel prompt6;
    private javax.swing.JLabel prompt7;
    private javax.swing.JLabel prompt8;
    private javax.swing.JLabel prompt9;
    // End of variables declaration//GEN-END:variables
}
